//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class controlPrintEntities : DbContext
    {
        public controlPrintEntities()
            : base("name=controlPrintEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Deposit> Deposits { get; set; }
        public virtual DbSet<EntityType> EntityTypes { get; set; }
        public virtual DbSet<PrintHistory> PrintHistories { get; set; }
        public virtual DbSet<Specialization> Specializations { get; set; }
        public virtual DbSet<SpecializationKind> SpecializationKinds { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Price> Prices { get; set; }
        public virtual DbSet<SizeOfPage> SizeOfPages { get; set; }
        public virtual DbSet<UserToSpec> UserToSpecs { get; set; }
    }
}
