//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserToSpec
    {
        public int userTospecId { get; set; }
        public int userId { get; set; }
        public int specId { get; set; }
    
        public virtual Specialization Specialization { get; set; }
        public virtual User User { get; set; }
    }
}
